<a href="https://colab.research.google.com/github/vuvincymol/FDSA/blob/main/FDSA_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.random.randint(10, size=6)
b = np.random.randint(10, size=(3, 4))
c = np.random.randint(10, size=(3, 4, 5))
print('One Diamensional Array\n',a)
print ('Two Diamensional Array\n',b)
print('Three Diamensional Array\n',c)
print('One Diamensional Attributes - Array name -a')
print("a ndim: ", a.ndim)
print("a shape:", a.shape)
print("a size: ", a.size)
print("dtype:", a.dtype)
print("itemsize:", a.itemsize, "bytes")
print("nbytes:", a.nbytes, "bytes")

print('Two Diamensional Attributes - Array name -b')
print("b ndim: ", b.ndim)
print("b shape:", b.shape)
print("b size: ", b.size)
print("dtype:", b.dtype)
print("itemsize:", b.itemsize, "bytes")
print("nbytes:", b.nbytes, "bytes")

print('Three Diamensional Attributes - Array name -c')
print("c ndim: ", c.ndim)
print("c shape:", c.shape)
print("c size: ", c.size)
print("dtype:", c.dtype)
print("itemsize:", c.itemsize, "bytes")
print("nbytes:", c.nbytes, "bytes")

print('One Diamensional Array name -a Printing Values Using Index')
print(a[::-1])

print('One Diamensional Array name -a Printing Values Using Index 2 to 5')
print(a[2:5])
print('2D Matrix\n',b)

print('Print 1st Row in Array\n',b[:1,:])
print('Print 1st Row in Array\n',b[1:2,:])
print('Print 2nd Row in Array\n',b[2:3,:])
print('Print 1st Column in Array\n',b[:,:1])
print('Print 2nd Coloumn in Array\n',b[:,1:2])
print('Print 4th Coloumn in Array\n',b[:,3:4])
print('Print Two Rows and Three Coloumn in Array\n',b[:2,:3])
b_sub=b[:2,:2]
print(b_sub)
b_sub[0,0]=50
b_sub[0,1]=100
b_sub[1,0]=150
b_sub[1,1]=200
print(b_sub)

print('Now 2D Array \n',b)
b_sub_copy = b[:2, :2].copy()
print('2D Array Using Copy Method\n]',b_sub_copy)
b_sub_copy[1,1]=300
print(b_sub_copy)
print('Now 2D Array \n',b)

print('The 1D Array \n',a)
a=a.reshape((2, 3))
print('Reshape Method 1D to 2D \n',a)
print(a)
a=a.reshape((6, 1))
print('Reshape Method\n',a)
a=a[:,np.newaxis]
print('Newaxis Method\n',a)
a=[1,2,3,4]
a1=[10,11,12,13]
print('Array 1',a)
print('Array 2',a1)
c=np.concatenate([a, a1])
print('Array Concatenation 1D\n', c)
print('Array 2D\n',b)
d=np.concatenate([b,b])
print('Array Concatenation 2D\n',d)
e=np.vstack([a, d])
print('Print Mixing Diamensional \n',e)
a=[1,2,3,4,5,6,7,8,9,10]
print('The New 1D array\n',a)
b3=np.split(a,[0,5])
print('The Array Split \nMethod\n',b3)

One Diamensional Array
 [5 4 5 6 2 3]
Two Diamensional Array
 [[4 0 9 5]
 [8 7 5 2]
 [7 3 4 1]]
Three Diamensional Array
 [[[3 3 2 5 8]
  [2 1 7 9 0]
  [4 8 9 3 3]
  [1 7 4 1 0]]

 [[5 2 2 8 0]
  [3 5 3 0 9]
  [7 3 9 4 7]
  [6 3 2 8 7]]

 [[4 0 8 5 2]
  [0 9 4 0 3]
  [9 0 5 5 2]
  [5 9 2 2 3]]]
One Diamensional Attributes - Array name -a
a ndim:  1
a shape: (6,)
a size:  6
dtype: int64
itemsize: 8 bytes
nbytes: 48 bytes
Two Diamensional Attributes - Array name -b
b ndim:  2
b shape: (3, 4)
b size:  12
dtype: int64
itemsize: 8 bytes
nbytes: 96 bytes
Three Diamensional Attributes - Array name -c
c ndim:  3
c shape: (3, 4, 5)
c size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes
One Diamensional Array name -a Printing Values Using Index
[3 2 6 5 4 5]
One Diamensional Array name -a Printing Values Using Index 2 to 5
[5 6 2]
2D Matrix
 [[4 0 9 5]
 [8 7 5 2]
 [7 3 4 1]]
Print 1st Row in Array
 [[4 0 9 5]]
Print 1st Row in Array
 [[8 7 5 2]]
Print 2nd Row in Array
 [[7 3 4 1]]
Print 1s